from datetime import datetime, timedelta
import os
import shutil
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.operators.bash import BashOperator
from airflow.providers.amazon.aws.hooks.s3 import S3Hook

BUCKET_NAME = os.environ.get("S3_BUCKET_NAME", "de-7-gwangyeongkim")
LOCAL_DATA_DIR = "/opt/airflow/data/pipeline"
LOCAL_CSV_PATH = f"{LOCAL_DATA_DIR}/netflix_titles.csv"
LOCAL_PARQUET_DIR = f"{LOCAL_DATA_DIR}/output_parquet"

default_args = {
    'owner': 'gwangyeong',
    'start_date': datetime(2026, 1, 1),
    'retries': 1,
    'retry_delay': timedelta(seconds=10),
}

def download_csv_from_s3(**context):
    os.makedirs(LOCAL_DATA_DIR, exist_ok=True)
    # aws_default Connection을 통해 안전하게 인증
    hook = S3Hook(aws_conn_id="aws_default")
    s3_key = "bronze/netflix_titles.csv"
    print(f"Downloading s3://{BUCKET_NAME}/{s3_key} to {LOCAL_CSV_PATH}...")
    
    # S3 파일 다운로드
    downloaded_file = hook.download_file(
        key=s3_key,
        bucket_name=BUCKET_NAME,
        local_path=LOCAL_DATA_DIR,
        preserve_file_name=True,
        use_autogenerated_subdir=False
    )
    # 지정한 파일명으로 위치 고정
    if downloaded_file != LOCAL_CSV_PATH:
        shutil.move(downloaded_file, LOCAL_CSV_PATH)

    file_size = os.path.getsize(LOCAL_CSV_PATH)
    print(f"Download complete: {file_size:,} bytes")

def upload_silver_to_s3(**context):
    today_str = context.get('ds', datetime.now().strftime("%Y-%m-%d"))
    s3_prefix = f"silver/{today_str}"
    hook = S3Hook(aws_conn_id="aws_default")
    
    uploaded_files = []
    for root, _, files in os.walk(LOCAL_PARQUET_DIR):
        for file in files:
            if file.endswith(".parquet"):
                local_path = os.path.join(root, file)
                s3_key = f"{s3_prefix}/{file}"
                print(f"Uploading {local_path} to s3://{BUCKET_NAME}/{s3_key}...")
                hook.load_file(
                    filename=local_path,
                    key=s3_key,
                    bucket_name=BUCKET_NAME,
                    replace=True
                )
                uploaded_files.append(s3_key)

    print(f"=== Silver Upload Completed ===")
    print(f"S3 Prefix: s3://{BUCKET_NAME}/{s3_prefix}/")
    print(f"Total uploaded files: {len(uploaded_files)}")
    for f in uploaded_files:
        print(f" - {f}")

with DAG(
    dag_id="weekly_pipeline_gwangyeong",
    default_args=default_args,
    schedule=None,
    catchup=False,
    tags=["q9", "week7"]
) as dag:

    # Task 1: S3 Bronze에서 CSV 다운로드
    download_csv = PythonOperator(
        task_id="download_csv",
        python_callable=download_csv_from_s3,
    )

    # Task 2: spark-submit으로 transform.py 실행
    transform = BashOperator(
        task_id="transform",
        bash_command=f"""
        spark-submit \
          --master local[*] \
          /opt/airflow/dags/jobs/transform.py \
          --input_path {LOCAL_CSV_PATH} \
          --output_path {LOCAL_PARQUET_DIR} \
          --release_year 2015
        """,
    )

    # Task 3: Parquet 결과를 S3 silver/{오늘날짜}로 업로드
    upload_silver = PythonOperator(
        task_id="upload_silver",
        python_callable=upload_silver_to_s3,
    )

    download_csv >> transform >> upload_silver